version: "2"
linters:
  default: fast
  disable:
    - depguard
    - mnd
    - prealloc
    - testpackage
  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - funlen
formatters:
  enable:
    - gofmt
    - gofumpt
    - golines
