[tools]
go = "1.26"
golangci-lint = "2.11.3"
goreleaser = "2.14.3"

[tasks.build]
description = "Build the project"
# If I run inside worktrees
run = "go build -buildvcs=false"

[tasks.lint]
description = "Lint the code with golangci-lint"
run = "golangci-lint run"

[tasks.format]
description = "Format the code with golangci-lint"
run = "golangci-lint fmt"

[tasks.test]
description = "Run tests"
run = "go test ./..."

[tasks.release]
description = "Release a new version"
run = "goreleaser release"

[tasks.readme]
description = "Update the README"
run = "go run ./internal/docs"

[tasks.bump]
description = "Create next semantic tag"
depends = ["format", "lint", "test"]
run = "go run ./internal/bump"
